function tem=shear_RGB(tem,sth,stw,dh,dw,line,color,maxc)
if strcmp(color,'g')||strcmp(color,'G')
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,1)=0;
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,2)=maxc;
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,3)=0;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,1)=0;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,2)=maxc;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,3)=0;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,1)=0;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,2)=maxc;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,3)=0;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,1)=0;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,2)=maxc;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,3)=0;
elseif strcmp(color,'r')||strcmp(color,'R') 
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,1)=maxc;
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,2)=0;
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,3)=0;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,1)=maxc;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,2)=0;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,3)=0;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,1)=maxc;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,2)=0;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,3)=0;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,1)=maxc;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,2)=0;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,3)=0;
elseif strcmp(color,'b')||strcmp(color,'B') 
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,1)=0;
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,2)=0;
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,3)=maxc;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,1)=0;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,2)=0;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,3)=maxc;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,1)=0;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,2)=0;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,3)=maxc;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,1)=0;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,2)=0;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,3)=maxc;
else
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,1)=maxc;
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,2)=maxc;
    tem(sth-line+1:sth,stw-line+1:stw+dw+line,3)=maxc;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,1)=maxc;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,2)=maxc;
    tem(sth+dh+1:sth+dh+line,stw-line+1:stw+dw+line,3)=maxc;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,1)=maxc;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,2)=maxc;
    tem(sth-line+1:sth+dh+line,stw-line+1:stw,3)=maxc;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,1)=maxc;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,2)=maxc;
    tem(sth-line+1:sth+dh+line,stw+dw+1:stw+dw+line,3)=maxc;
end